"""End-to-end test for the `ctx` (cisTarget) step.

`ctx` normally needs a multi-GB ranking database, so it can't use the big public
DBs in CI. Instead this runs against tiny synthetic fixtures (data/ctx_mini.*)
generated by tests/_make_ctx_fixture.py: one motif is built to recover TF1's
module near the top of the ranking (NES ~ 4.4, well over the 3.0 threshold) while
the rest are flat, so ctx deterministically returns a single TF1(+) regulon.

This exercises the whole Rust path -- Arrow ranking-DB reader, module building,
recovery-curve/NES math, motif annotation, and leading-edge pruning.
"""

from pathlib import Path

import numpy as np
import pandas as pd
import pytest
import scenic_rs as srs

DATA = Path(__file__).resolve().parents[1] / "data"
DB = DATA / "ctx_mini.feather"
MOTIFS = DATA / "ctx_mini_motifs.tbl"

# Must match tests/_make_ctx_fixture.py.
TF = "TF1"
TARGETS = [f"t{i:02d}" for i in range(25)]
MODULE = [TF] + TARGETS


def make_ctx_inputs():
    """Deterministic expression + adjacencies for TF1 and its 25 targets.

    Targets are generated from a shared latent signal so they positively
    correlate with TF1 -> the module is classified activating (+).
    """
    rng = np.random.default_rng(0)
    n_cells = 200
    z = rng.standard_normal(n_cells)
    cols = [z + 0.2 * rng.standard_normal(n_cells)]  # TF1
    cols += [z + 0.3 * rng.standard_normal(n_cells) for _ in TARGETS]
    X = np.ascontiguousarray(np.stack(cols, axis=1), dtype=np.float32)

    adj = pd.DataFrame(
        {
            "TF": [TF] * len(TARGETS),
            "target": TARGETS,
            "importance": [float(len(TARGETS) - i) for i in range(len(TARGETS))],
        }
    )
    return adj, X, MODULE


@pytest.fixture(scope="module")
def fixtures_present():
    if not (DB.exists() and MOTIFS.exists()):
        pytest.skip("ctx fixtures missing; regenerate with tests/_make_ctx_fixture.py")


def test_ctx_returns_expected_regulon(fixtures_present):
    adj, X, gene_names = make_ctx_inputs()

    regulons = srs.ctx(
        adj, X, gene_names, [(str(DB), "ctx_mini")], str(MOTIFS), min_genes=10
    )

    assert isinstance(regulons, list)
    assert len(regulons) == 1

    reg = regulons[0]
    assert reg.tf == TF
    assert reg.name == "TF1(+)"
    assert reg.activating is True
    assert reg.nes > 3.0
    # Leading-edge genes are a subset of the module; the TF itself is included.
    assert set(reg.genes).issubset(set(gene_names))
    assert TF in reg.genes
    assert len(reg.genes) >= 10
    assert len(reg.genes) == len(reg.weights)
    assert np.isfinite(np.asarray(reg.weights, dtype=float)).all()


def test_ctx_is_deterministic(fixtures_present):
    adj, X, gene_names = make_ctx_inputs()
    kw = dict(min_genes=10)
    a = srs.ctx(adj, X, gene_names, [(str(DB), "ctx_mini")], str(MOTIFS), **kw)
    b = srs.ctx(adj, X, gene_names, [(str(DB), "ctx_mini")], str(MOTIFS), **kw)
    assert [(r.name, sorted(r.genes)) for r in a] == [
        (r.name, sorted(r.genes)) for r in b
    ]
